### ISSUE TITLE
Controllers doesnt work in pavlov

### ISSUE THREAD

**Issue by Martin1245** [psmoveservice/PSMoveService#637]
Hi in almost every game controllers work but in Pavlov they are stuck on the ground and no buttons work controllers just completely doesnt work.When i press the playstation button steam shows up and controllers work when i get back in game they stop working.This happen only in pavlov. Any suggestions?

**Comment by NikitaShokin** [comment]
You have pirate pavlov? Have you tried to play other vr games to test input? (some free like surgeon simulator vr: meet the medic)

**Comment by Martin1245** [comment]
No i have Pavlov on steam.And i tried other games like RecRoom,Beatsaber,Zombie trainer and it work fine but from all  games i tried Pavlov just doesnt work.They are just stuck on the ground doing nothing like the controllers are not connected or something

**Comment by NikitaShokin** [comment]
You can try to downgrade steamvrbrige. I now trying to play beat saber (pirate) and buttons does not work in game (only ps button opening steam overlay). I will write you if i have sucsess
(sorry of my english)

**Comment by NikitaShokin** [comment]
Downgrading PSMoveSteamVRBrige doesn't work :( (i tried versions 1.5.0 and 1.4.2 )

**Comment by Martin1245** [comment]
Never mind i will keep trying to fix it but i will be leaving for 10 days so no time now.

**Comment by NikitaShokin** [comment]
Ok, good luck

**Comment by cboulay** [comment]
This isn't a PSMoveService problem. Please move discussion to PSMoveSteamVRBrige.
