### ISSUE TITLE
Controllers doesnt work in some games

### ISSUE THREAD

**Issue by Martin1245** [psmoveservice/PSMoveService#641]
Controllers are stuck in ground and completely not working in some games.When i press PS button steam opens and they work.Any suggestion? PLEASE

**Comment by NikitaShokin** [comment]
You have pirate beatsaber? Have you tried to play other vr games to test input? (some free like surgeon simulator vr: meet the medic)

**Comment by switelolo124** [comment]
i have simmilar issue, in ex, in pirated skyrim vr, i can press few times "next" and when game tell me to move i cant, i cant see controller in skyrim, in The lab on steam also i cant see controllers, portal stories vr is not working at all, on my oculus dk2 is black screen and controllers also not work, but ex. in VRchat everything working good, Any help for that ?

**Comment by cboulay** [comment]
Please moe conversation to PSMoveSteamVRBrige
