### ISSUE TITLE
Move controllers not working in some games

### ISSUE THREAD

**Issue by KrishPatel123** [psmoveservice/PSMoveService#646]
I actually have two problems, I downloaded 1.6 Psmoveservice with the new steam input system. But I still have the old drivers installed on steamvr and do not know to delete. This makes some games not work like vivecraft 1.14.4 BUT older versions that use openvr instead of steamvr work.

Also, another problem is my bindings. I want to change it so the 4 buttons relate to the four touchpad_directions. I could do this within the steamvr.settings but now with the new input manager, there is no option for that. I thought i should just change the legacy bings but idk.

Would be great if I could get some help.

btw everything works fine in SteamVr Home and other games.

**Comment by cboulay** [comment]
Move to PSMoveSteamVRBrige
