### ISSUE TITLE
I can only pair one controller.

### ISSUE THREAD

**Issue by qwFaTE** [psmoveservice/PSMoveService#649]
Hey, so I've had this stuff for over a year now, it never worked for me on Windows 7 but I've recently upgraded to Windows 10 so I decided to give it another shot. I can't even get as far as where I did in Windows 7. Only one controller paired. It took around 8 minutes of button mashing for it to finally pair, which seems a lot longer than what tutorials show. After mashing the other controller's button for 20 minutes straight and it still wouldn't pair; I can only assume that something is wrong. I really want this to work. I'm using the PS3 move controllers, 2 PSeyes which have the libusb drivers set up. I'm running Win10 and am using a DK2 if that has anything to do with it. Please help.

The controllers should work fine, as they once paired no problem back on my Win7 machine.

Thank you.

**Comment by kaosjr** [comment]
I''m having this same issue. DK2, 2 motion controllers. One pairs fine, the other won't pair at all. Using the 1903 build to get one of them to pair, the other one is showing up in my Bluetooth menu but won't pair. I've tried uninstalling the device through device manager (which did nothing) and through Bluetooth (which just tells me that 'remove failed' for some reason). Any help?

**Comment by kaosjr** [comment]
I manged to get the remove to succeed by turning the bluetooth off and back on. Try that @qwFaTE ?

**Comment by qwFaTE** [comment]
Any particular time when to do that? I've tried restarting bluetooth before pairing and mid-pairing, but to no avail. When did you restart bluetooth? Also, how would I get the 1903 build? All of the releases are marked as #X.X.X in their version numbers. Thank you for the reply!

**Comment by NikitaShokin** [comment]
try #634

**Comment by qwFaTE** [comment]
Thank you so much, @NikitaShokin ! Worked like a charm, much appreciated!
