### ISSUE TITLE
Do I still need a 3rd move controller to get the virtual hmd setup?

### ISSUE THREAD

**Issue by aShadyy** [psmoveservice/PSMoveService#651]
As the title says, Do I still need a 3rd move controller to get the virtual hmd setup? Or is it different? Most info are 2 years old so it might have changed. Can i just use a dual shock 4 controller for the orientation or something?

**Comment by NikitaShokin** [comment]
If you have gyroscope in your phone, you only need a glowing sphere to track your head. You can use ping-pong ball with light-emitting diode

**Comment by aShadyy** [comment]
Yes but I was watching Daley tech's video and he mentioned that an extra move controller is needed durkng the intial setup. I indeed have a gyroscope in my phone.

**Comment by NovaPlayzGames** [comment]
that has changed you do not need one now he posted a update video on that but the tracking is non existent with the psmove service in its current state

**Comment by aShadyy** [comment]
@NovaPlayzGames This was the exact answer I was looking for. Thank you so much.
Also thank you @NikitaShokin !
