### ISSUE TITLE
Ps Move controllers not working in game (Only buttons)

### ISSUE THREAD

**Issue by ChrisYOLO** [psmoveservice/PSMoveService#660]
The setup is done everything works in the bridge and in the setup (not steam) but when i start everything and i get into the steam vr home i can use the controllers but the buttons doesn't work... I tried everything but still i can't fix it. Plus+++ My head tracking is being detected in the service but not ingame (steam vr home and on other games)

**Comment by switelolo124** [comment]
Did u copy config file to steamvr folder ? or did u create by yourself ?

**Comment by cboulay** [comment]
Move to PSMoveSteamVRBrige
