### ISSUE TITLE
Cannot pair motion controller.

### ISSUE THREAD

**Issue by JarekStudio** [psmoveservice/PSMoveService#665]
Hello, I have 2 ps move controllers from ps3. PsMoveService see them, but when I unplug usb cable to pair them it says:
![Screenshot_2](https://user-images.githubusercontent.com/47699665/70718597-ca4d1700-1cf0-11ea-8f7e-96d8884c5215.png)
![Screenshot_4](https://user-images.githubusercontent.com/47699665/70718598-ca4d1700-1cf0-11ea-9c40-4a9543a0de83.png)
![Screenshot_5](https://user-images.githubusercontent.com/47699665/70718599-ca4d1700-1cf0-11ea-858d-890b6cecd068.png)

Could someone help me?

**Comment by James-Steward** [comment]
How were you able to solve this?
