### ISSUE TITLE
I can't pair my ps move controllers

### ISSUE THREAD

**Issue by Porazzh** [psmoveservice/PSMoveService#696]
I've tried everything please help i have windows 10 Pro 1909v.
I think the only way is degree my windows to 1809

**Comment by AgoniXX** [comment]
1909 is working fine.
Something should be wrong with your config.

**Comment by Swaiiler48** [comment]
Is there a way that will fix the issue with ZCM1R controller? tThat is what I have, and I can only pair one of my controllers.

**Comment by Porazzh** [comment]
Thank you all. Worked when i pair ps4 controller to computer unpair and pair ps move and works :D
