### ISSUE TITLE
PS Move controllers (ZCM 2) don`t show up in settings

### ISSUE THREAD

**Issue by V0RTT3X** [psmoveservice/PSMoveService#700]
I paired the Controllers via the Config Tool, but when I was done they don`t showed up in the settings menu and the red light of the controller turned off. If I`m trying to add them via Win10 and pair them with my Bluetooth adapter, the connection to the PSMove Config tool is lost and I can`t reconnect.

**Comment by seene** [comment]
hey,
try to delete them in windows 10 settings (windows restart) 
and try to reconnect them in config tool (with usb cable)

**Comment by V0RTT3X** [comment]
I fixed it via #634, downloading the new PSMoveServiceAdmin to pair the controllers. Thx for the reply
