### ISSUE TITLE
Pairing successful with one PSMove Controller but not the other?

### ISSUE THREAD

**Issue by AegeanStudios** [psmoveservice/PSMoveService#714]
Hi, am setting up PSMoveService, and having issues with my psmove controller. One of them pairs without issue, straight away - the other, gives the following output repetatively:
```
[2020-05-31 18:20:45.545]: AsyncBluetoothPairDeviceRequest - Bluetooth device found matching the given address: 00:07:04:42:ee:b2
[2020-05-31 18:20:45.551]: AsyncBluetoothPairDeviceRequest - Bluetooth device matching the given address is the expected controller type
[2020-05-31 18:20:45.559]: AsyncBluetoothPairDeviceRequest - Connection attempt: 0/80
[2020-05-31 18:20:45.563]: AsyncBluetoothPairDeviceRequest - Patching the registry ...
[2020-05-31 18:20:45.568]: AsyncBluetoothPairDeviceRequest - Get VirtuallyCabled: 1
[2020-05-31 18:20:45.571]: AsyncBluetoothPairDeviceRequest - Checking HID service
[2020-05-31 18:20:45.576]: AsyncBluetoothPairDeviceRequest - HID service not enabled, attempting to enable
[2020-05-31 18:20:45.581]: AsyncBluetoothPairDeviceRequest - Failed to enable HID service. Error code: 1060
```
I have tried resetting the psmove, while plugged into the PS3 or not, resetting the PS3 settings it was prior paired to (it still is paired to it, although I noted the PS3 does not recognise it as a bluetooth device, despite it being paired) and removing my bluetooth radio driver in device manager, and letting it reinstall - to no effect. This controller has been paired to this PC and dongle in the past, so I do not know why it is not working right now.

EDIT: Both controllers are SN: CECH-ZCM1E

**Comment by Eerovil** [comment]
"Forget" the device in windows bluetooth settings. If pairing still doesn't work try the custom build here:  https://github.com/psmoveservice/PSMoveService/issues/652#issuecomment-558433284

**Comment by AegeanStudios** [comment]
Neither had any effect - there was a controller referenced as "paired" in windows settings, however I believe that to be my successfully pairing one, as it had no effect to unpair it. I replaced my build with the one in the comment thread, to no effect. I do note that while trying to pair, windows recognises the controller in the action center, with "Connected (1)" but that's the only sign of a link.

**Comment by Eerovil** [comment]
Can you pair it to the PS3 and it works?

**Comment by AegeanStudios** [comment]
Yes and no - It doesn't recognise it as being paired/registered, and won't recognise it while scanning, however does connect to the console and can then on be used as a functional motion controller.

**Comment by Eerovil** [comment]
Resetting the controller using a paperclip could work.

**Comment by AegeanStudios** [comment]
That was what i meant by resetting the PSMove - I haven't taken the time to delete and resetup my config, because... well, effort really - I have deleted the config file for the given PSMove that i'm having issues with, which (say it with me now) had no effect.

**Comment by AegeanStudios** [comment]
Issue Resolved: I deleted the dongles, the devices and the config file for the offending controller, then built from source, which finally worked.

**Comment by cmoslinker** [comment]
Hy
Still doesn't work for me with the last PSMoveServiceAdmin.exe (july 2019) and the PSConfigTool.exe.
The first PSMove behaves well but not the second…
No problem to pair one or the other…
During the pairing process it remains blocked at step 2...
I tried to remove the motion controller from the Bluetooth menu (others or keyboard…) without sucess…
Please help !

![PSMove pairing3](https://user-images.githubusercontent.com/66915468/84599074-9f927580-ae6f-11ea-90c7-44883247ae2f.jpg)
![PSMove pairing1](https://user-images.githubusercontent.com/66915468/84598901-54c42e00-ae6e-11ea-9616-edfd2ee2b96f.jpg)
![PSMove pairing2](https://user-images.githubusercontent.com/66915468/84598938-a2409b00-ae6e-11ea-85c7-6921454ceba4.jpg)

**Comment by AegeanStudios** [comment]
Try removing the bluetooth radio in either device manager or windows settings. You also may want to try the build in the earlier comment, or building from source.

**Comment by cmoslinker** [comment]
I tried to remove the Bluetooth dongle with no success and I don't know how to build from source...in fact I never tried...is there a tutorial ?
