### ISSUE TITLE
Emulate VIVE controllers

### ISSUE THREAD

**Issue by shrekster2** [psmoveservice/PSMoveService#721]
Hello everyone, I have everything working and it's great except for one thing, I can't control a lot of games. So is there a work around for this? I have heard of people being able to emulate vive controllers, how do i fix this?

**Comment by shrekster2** [comment]
i see this is a very active repo

**Comment by cboulay** [comment]
It isn't.
And I'm tired of telling people that this repo has nothing to do with getting psmove controllers to work in games. I have never attempted that and I have no intention of doing so.
Maybe you can search the issues in https://github.com/HipsterSloth/PSMoveSteamVRBridge

Both repos share the same google group, but you won't get any answers from me on anything having to do with "it doesn't work in game X".
