### ISSUE TITLE
I found this file: https://1drv.ms/u/s!An8ls2qnV1z_n_57p7s2utrsq_x0LQ I think it's be useful to some seekers like me)

### ISSUE THREAD

**Issue by StIruy** [psmoveservice/PSMoveService#754]
I found this file: https://1drv.ms/u/s!An8ls2qnV1z_n_57p7s2utrsq_x0LQ I think it's be useful to some seekers like me)

_Originally posted by @NikitaShokin in https://github.com/psmoveservice/PSMoveService/issues/634#issuecomment-529177507_

Excuse me, can you tell me where I can get this file now?

**Comment by Personne0012** [comment]
You should build from master to have pairing working, but if this can help here's my build (x64).
https://drive.google.com/file/d/1PoKvFL6MZF2NsF9-nr4Hhzn11zSHLiT9/view?usp=sharing

**Comment by StIruy** [comment]
Can you tell me what I need to do with this, I think I'm doing something wrong

**Comment by Personne0012** [comment]
This is just a built from master which include fix for psmove pairing (use PSMoveServiceAdmin.exe)

**Comment by StIruy** [comment]
When I run this file, I see error like that "path D:\Persone\... not found"

**Comment by StIruy** [comment]
Thanks

**Comment by Personne0012** [comment]
Try to delete "shared_mem" folder in "PSMoveService-x64\psmoveservice\Release" directory, those files are created at first launch and i think it register in some way my file tree.
